# Site settings
title: 
header-img: img/home-bg.png
email: devani@flatironschool.com
copyright_name: thoughtsailor
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  thoughtsailor
learn_profile: thoughtsailor
email_username: devani@flatironschool.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
